export const types={
    LOGIN:"LOGIN",
    REGISTER:"REGISTER",
    SET_USER_DATA:"SET_USER_DATA",
    RENDER:"RENDER",
    CREATE_PROFILE:"CREATE_PROFILE",
    EDIT_PROFILE:"EDIT_PROFILE",
    DELETE_PROFILE:"DELETE_PROFILE"
}